services:
  - type: web
    name: sbtpremios-clone
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PIX_KEY
        value: sbtpremios@ilotto.com.br
